name: email_classifier
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - transformers
  - pip
  - pip:
    - torch==1.9.0