name: email_classifier
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.4.2
  - scikit-learn=1.0.2
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3
  - transformers=4.18.0
  - pip=22.0.4